
SELECT SMS.CALLING_NUMBER NUM_TEL     
      ,COUNT (DISTINCT(CASE WHEN EXTRACT(DOW FROM SMS.MESSAGE_DELIVERYTIME) = 1 THEN CAST(SMS.CALLING_NUMBER AS VARCHAR(20)) END )) CANT_SMS_ENV_DOM
	  ,COUNT (DISTINCT(CASE WHEN EXTRACT(DOW FROM SMS.MESSAGE_DELIVERYTIME) = 2 THEN CAST(SMS.CALLING_NUMBER AS VARCHAR(20)) END )) CANT_SMS_ENV_LUN
	  ,COUNT (DISTINCT(CASE WHEN EXTRACT(DOW FROM SMS.MESSAGE_DELIVERYTIME) = 3 THEN CAST(SMS.CALLING_NUMBER AS VARCHAR(20)) END )) CANT_SMS_ENV_MAR
	  ,COUNT (DISTINCT(CASE WHEN EXTRACT(DOW FROM SMS.MESSAGE_DELIVERYTIME) = 4 THEN CAST(SMS.CALLING_NUMBER AS VARCHAR(20)) END )) CANT_SMS_ENV_MIE
	  ,COUNT (DISTINCT(CASE WHEN EXTRACT(DOW FROM SMS.MESSAGE_DELIVERYTIME) = 5 THEN CAST(SMS.CALLING_NUMBER AS VARCHAR(20)) END )) CANT_SMS_ENV_JUE
	  ,COUNT (DISTINCT(CASE WHEN EXTRACT(DOW FROM SMS.MESSAGE_DELIVERYTIME) = 6 THEN CAST(SMS.CALLING_NUMBER AS VARCHAR(20)) END )) CANT_SMS_ENV_VIE
	  ,COUNT (DISTINCT(CASE WHEN EXTRACT(DOW FROM SMS.MESSAGE_DELIVERYTIME) = 7 THEN CAST(SMS.CALLING_NUMBER AS VARCHAR(20)) END )) CANT_SMS_ENV_SAB
 FROM  DWH_DB.MDRS.SMSMMS SMS  
       INNER JOIN DB_DWH_DESARROLLO.ECM5461E.TBL_PREPAGO_COMSUMOS_SEMANAL_201807 SEM ON '57'||SEM.NUMERO_TELEFONO = SMS.CALLING_NUMBER
 WHERE SMS.MESSAGE_DELIVERYTIME BETWEEN '2018-07-01 00:00:00' AND '2018-07-31 23:59:59'
   AND SMS.CAUSE_FOR_TERMINATION = '100C'
   AND SMS.RECORD_TYPE = 2   
 GROUP BY 1
 LIMIT 10