
SELECT TELE_NUMB NUMERO_TEL
,COUNT(TELE_NUMB) TOTAL_REGISTROS_MES
,SUM(CANT_CARGAS) CANT_RECARGAS
,ROUND(SUM(VLR_CARGAS)) TOTAL_VLR_REC
,ROUND(SUM(VLR_CONSUMO_VOZ)) TOTAL_VLR_CONSUMO_VOZ
,ROUND(SUM(VLR_CONSUMO_SMS)) TOTAL_VLR_CONSUMO_SMS
,ROUND(SUM(ARPU_PREPAGO)) TOTAL_ARPU
FROM DB_DWH_DESARROLLO.ECM5461E.TBL_PREPAGO_RECARPU_201807
GROUP BY 1
LIMIT 10