
SELECT CALLING_NUMBER
      ,SUM(CASE WHEN EXTRACT(DOW FROM FECHA_HORA) = 1 THEN 1  ELSE 0 END) CANT_LLAM_DOM
      ,SUM(CASE WHEN EXTRACT(DOW FROM FECHA_HORA) = 1 THEN DURACION  ELSE 0 END) DUR_LLAM_DOM
      ,COUNT (DISTINCT(CASE WHEN EXTRACT(DOW FROM FECHA_HORA) = 1 THEN CAST(CALLED_NUMBER AS VARCHAR(20)) END )) CANT_CONTAC_UNICOS_DOM
 FROM  DB_DWH_VOZ.VOZ.TBL_FACT_VOZ_TRAFICO_SALIENTE VOZ  
       INNER JOIN DWH_DB.SEGMENTACION.INH_SEG_BSCS_CLIENTES CLI ON CLI.TELE_NUMB = VOZ.CALLING_NUMBER
 WHERE VOZ.FECHA_HORA BETWEEN '2018-07-01 00:00:00' AND '2018-07-31 23:59:59'
   AND CLI.TIPO_LINEA = 'Prepago'
   AND CLI.ESTADO = 'a'   
 GROUP BY CALLING_NUMBER
 